/*
    날짜 : 2025/07/18
    이름 : 김철학
    내용 : SQL 연습문제1
*/
-- 실습 1-1
ALTER SESSION SET "_ORACLE_SCRIPT"=true;
create user shop identified by 1234;
grant connect, resource, unlimited tablespace to shop;

-- 실습 1-2
drop table orders;
create table customer (
    CID         VARCHAR2(20) PRIMARY KEY,
    NAME        VARCHAR2(20) NOT NULL,
    HP          CHAR(13) UNIQUE,
    ADDRESS     VARCHAR2(200),
    RDATE       DATE NOT NULL
);

create table product (
    pno     NUMBER(4) PRIMARY KEY,
    pname   VARCHAR2(30) NOT NULL,
    stock   NUMBER DEFAULT 0,
    price   NUMBER,
    company VARCHAR2(20)
);

create table orders (
    ord_no    NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ord_cid   VARCHAR2(20) NOT NULL,
    ord_pno   NUMBER(4) NOT NULL,
    ord_cnt   NUMBER DEFAULT 1,
    ord_date  DATE NOT NULL
);

-- 실습 1-3
insert into customer values ('c101', '김유신', '010-1234-1001', '김해시 봉황동', '2022-01-01');
insert into customer values ('c102', '김춘추', '010-1234-1002', '경주시 보문동', '2022-01-02');
insert into customer values ('c103', '장보고', '010-1234-1003', '완도군 청산면', '2022-01-03');
insert into customer values ('c104', '강감찬', '010-1234-1004', '서울시 마포구', '2022-01-04');
insert into customer values ('c105', '이성계', NULL, NULL, '2022-01-05');
insert into customer values ('c106', '정철', '010-1234-1006', '경기도 용인시', '2022-01-06');
insert into customer values ('c107', '허준', NULL, NULL, '2022-01-07');
insert into customer values ('c108', '이순신', '010-1234-1008', '서울시 영등포구', '2022-01-08');
insert into customer values ('c109', '송상현', '010-1234-1009', '부산시 동래구', '2022-01-09');
insert into customer values ('c110', '정약용', '010-1234-1010', '경기도 광주시', '2022-01-10');

insert into product values (1, '새우깡', 5000, 1500, '농심');
insert into product values (2, '초코파이', 2500, 2500, '오리온');
insert into product values (3, '포카칩', 3600, 1700, '오리온');
insert into product values (4, '양파링', 1250, 1800, '농심');
insert into product values (5, '죠리퐁', 2200, NULL, '크라운');
insert into product values (6, '마가렛트', 3500, 3500, '롯데');
insert into product values (7, '뿌셔뿌셔', 1650, 1200, '오뚜기');

insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c102', 3, 2, '2022-07-01 13:15:10');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c101', 4, 1, '2022-07-01 14:16:11');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c108', 1, 1, '2022-07-01 17:23:18');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c109', 6, 5, '2022-07-01 10:46:36');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c102', 2, 1, '2022-07-03 09:15:37');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c101', 7, 3, '2022-07-03 12:35:12');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c110', 1, 2, '2022-07-03 16:55:36');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c104', 2, 4, '2022-07-04 14:23:23');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c102', 1, 3, '2022-07-04 21:54:34');
insert into orders (ORD_CID, ORD_PNO, ORD_CNT, ORD_DATE) values ('c107', 6, 1, '2022-07-05 14:21:03');

-- 실습 1-4
select * from product;

-- 실습 1-5
-- 실습 1-6
-- 실습 1-7
-- 실습 1-8
-- 실습 1-9
-- 실습 1-10
-- 실습 1-11
-- 실습 1-12
-- 실습 1-13
-- 실습 1-14
-- 실습 1-15
-- 실습 1-16
-- 실습 1-17
-- 실습 1-18
-- 실습 1-19
-- 실습 1-20
-- 실습 1-21
-- 실습 1-22
-- 실습 1-23
-- 실습 1-24
-- 실습 1-25
-- 실습 1-26
-- 실습 1-27
-- 실습 1-28
-- 실습 1-29
-- 실습 1-30